"""Phase 2 laboratory-owned manufacturer and instrument master data.

Revision ID: 0002_phase2
Revises: 0001_phase1
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "0002_phase2"
down_revision = "0001_phase1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "manufacturers",
        sa.Column("laboratory_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("registration_no", sa.String(length=200), nullable=True),
        sa.Column("address", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("contact_person", sa.String(length=200), nullable=True),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("phone", sa.String(length=200), nullable=True),
        sa.Column("country", sa.String(length=200), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lock_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "address ? 'schema_version' AND address->>'schema_version' = '1' AND "
            "jsonb_typeof(address) = 'object'",
            name="ck_manufacturer_address",
        ),
        sa.CheckConstraint("lock_version > 0", name="ck_manufacturer_version"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["laboratory_id"], ["laboratories.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "laboratory_id", name="uq_manufacturer_lab"),
    )
    op.create_index(
        "ix_manufacturer_lab_name", "manufacturers", ["laboratory_id", "name"], unique=False
    )
    op.create_table(
        "instruments",
        sa.Column("laboratory_id", sa.Uuid(), nullable=False),
        sa.Column("manufacturer_id", sa.Uuid(), nullable=False),
        sa.Column("model_name", sa.String(length=200), nullable=False),
        sa.Column("type_designation", sa.String(length=200), nullable=True),
        sa.Column("serial_number", sa.String(length=200), nullable=True),
        sa.Column("accuracy_class", sa.String(length=4), nullable=False),
        sa.Column("verification_intervals_n", sa.Numeric(), nullable=False),
        sa.Column("range_type", sa.String(length=200), nullable=True),
        sa.Column("indication_type", sa.String(length=200), nullable=True),
        sa.Column("is_self_indicating", sa.Boolean(), nullable=True),
        sa.Column("is_electronic", sa.Boolean(), nullable=True),
        sa.Column("is_software_controlled", sa.Boolean(), nullable=True),
        sa.Column("is_portable", sa.Boolean(), nullable=True),
        sa.Column("is_mobile", sa.Boolean(), nullable=True),
        sa.Column("load_receptor_type", sa.String(length=200), nullable=True),
        sa.Column("support_point_count", sa.Integer(), nullable=True),
        sa.Column("tare_type", sa.String(length=200), nullable=True),
        sa.Column("maximum_tare_g", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("zero_setting_type", sa.String(length=200), nullable=True),
        sa.Column("zero_tracking_available", sa.Boolean(), nullable=True),
        sa.Column("level_indicator_available", sa.Boolean(), nullable=True),
        sa.Column("automatic_tilt_sensor", sa.Boolean(), nullable=True),
        sa.Column("power_supply_type", sa.String(length=200), nullable=True),
        sa.Column("nominal_voltage", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("min_voltage", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("max_voltage", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("declared_temp_min_c", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("declared_temp_max_c", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("software_identifier", sa.String(length=200), nullable=True),
        sa.Column(
            "instrument_status", sa.String(length=20), server_default="ACTIVE", nullable=False
        ),
        sa.Column("metadata_schema_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lock_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("max_capacity_g", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("min_capacity_g", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("scale_interval_d_g", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("verification_interval_e_g", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.CheckConstraint("accuracy_class IN ('I','II','III','IIII')", name="ck_instrument_class"),
        sa.CheckConstraint(
            "instrument_status IN ('ACTIVE','ARCHIVED')", name="ck_instrument_status"
        ),
        sa.CheckConstraint(
            "max_capacity_g > 0 AND max_capacity_g <> 'NaN'::numeric AND "
            "scale_interval_d_g > 0 AND scale_interval_d_g <> 'NaN'::numeric AND "
            "verification_interval_e_g > 0 AND verification_interval_e_g <> "
            "'NaN'::numeric",
            name="ck_instrument_positive",
        ),
        sa.CheckConstraint(
            "metadata_schema_version = 1 AND jsonb_typeof(metadata_json) = 'object'",
            name="ck_instrument_metadata",
        ),
        sa.CheckConstraint(
            "(nominal_voltage IS NULL OR nominal_voltage > 0) AND (min_voltage IS NULL OR "
            "min_voltage > 0) AND (max_voltage IS NULL OR max_voltage > 0) AND "
            "(min_voltage IS NULL OR max_voltage IS NULL OR min_voltage <= max_voltage) "
            "AND (nominal_voltage IS NULL OR min_voltage IS NULL OR nominal_voltage >= "
            "min_voltage) AND (nominal_voltage IS NULL OR max_voltage IS NULL OR "
            "nominal_voltage <= max_voltage)",
            name="ck_instrument_voltages",
        ),
        sa.CheckConstraint(
            "declared_temp_min_c IS NULL OR declared_temp_max_c IS NULL OR "
            "declared_temp_min_c <= declared_temp_max_c",
            name="ck_instrument_temperatures",
        ),
        sa.CheckConstraint("lock_version > 0", name="ck_instrument_version"),
        sa.CheckConstraint(
            "maximum_tare_g IS NULL OR maximum_tare_g >= 0", name="ck_instrument_tare"
        ),
        sa.CheckConstraint(
            "min_capacity_g IS NULL OR (min_capacity_g >= 0 AND min_capacity_g < max_capacity_g)",
            name="ck_instrument_min",
        ),
        sa.CheckConstraint(
            "support_point_count IS NULL OR support_point_count > 0", name="ck_instrument_supports"
        ),
        sa.CheckConstraint(
            "verification_intervals_n > 0 AND verification_intervals_n * "
            "verification_interval_e_g = max_capacity_g",
            name="ck_instrument_exact_n",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["laboratory_id"], ["laboratories.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["manufacturer_id", "laboratory_id"],
            ["manufacturers.id", "manufacturers.laboratory_id"],
            name="fk_instrument_manufacturer_lab",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_instrument_lab_manufacturer",
        "instruments",
        ["laboratory_id", "manufacturer_id"],
        unique=False,
    )
    op.create_table(
        "instrument_components",
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("component_type", sa.String(length=200), nullable=False),
        sa.Column("manufacturer_name", sa.String(length=200), nullable=True),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column("serial_or_type", sa.String(length=200), nullable=True),
        sa.Column("certificate_reference", sa.String(length=200), nullable=True),
        sa.Column(
            "technical_specifications", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lock_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "technical_specifications ? 'schema_version' AND "
            "technical_specifications->>'schema_version' = '1' AND "
            "jsonb_typeof(technical_specifications) = 'object'",
            name="ck_component_schema",
        ),
        sa.CheckConstraint("lock_version > 0", name="ck_component_version"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_instrument_components_instrument_id"),
        "instrument_components",
        ["instrument_id"],
        unique=False,
    )
    op.create_table(
        "instrument_ranges",
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("range_no", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lock_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("max_capacity_g", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("min_capacity_g", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("scale_interval_d_g", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("verification_interval_e_g", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.CheckConstraint(
            "max_capacity_g > 0 AND max_capacity_g <> 'NaN'::numeric AND "
            "scale_interval_d_g > 0 AND scale_interval_d_g <> 'NaN'::numeric AND "
            "verification_interval_e_g > 0 AND verification_interval_e_g <> "
            "'NaN'::numeric",
            name="ck_range_positive",
        ),
        sa.CheckConstraint("lock_version > 0", name="ck_range_version"),
        sa.CheckConstraint(
            "min_capacity_g IS NULL OR (min_capacity_g >= 0 AND min_capacity_g < max_capacity_g)",
            name="ck_range_min",
        ),
        sa.CheckConstraint("range_no > 0", name="ck_range_number"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("instrument_id", "range_no", name="uq_instrument_range_no"),
    )
    op.create_index(
        op.f("ix_instrument_ranges_instrument_id"),
        "instrument_ranges",
        ["instrument_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("instrument_ranges")
    op.drop_table("instrument_components")
    op.drop_table("instruments")
    op.drop_table("manufacturers")
    # ### end Alembic commands ###
